# Generated by Django 4.0.1 on 2022-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('other', 'other'), ('salary', 'salary'), ('pension', 'pension'), ('rent', 'rent'), ('utilities', 'utilities'), ('groceries', 'groceries'), ('health', 'health'), ('gym', 'gym'), ('travel', 'travel'), ('car', 'car'), ('extras', 'extras'), ('eating out', 'eating out')], default='other', max_length=200)),
                ('expense_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=200)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(choices=[('one-off', 'one-off'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='one-off', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField()),
            ],
        ),
    ]
